-- 4.6
GRANT ALL PRIVILEGES ON TABLE STUDENT,CLASS TO U1 WITH GRANT OPTION;
GRANT SELECT,UPDATE(HOME) ON TABLE STUDENT TO U2;
GRANT SELECT ON TABLE CLASS TO PUBLIC;
GRANT SELECT,UPDATE ON TABLE STUDENT TO R1;
GRANT R1 TO U1 WITH ADMIN OPTION;

-- 4.7
GRANT SELECT ON TABLE EMPLOYEE,DEPARTMENT TO WANGMING;
GRANT INSERT,DELETE ON TABLE EMPLOYEE,DEPARTMENT TO LIYONG;
GRANT SELECT ON TABLE EMPLOYEE WITH USER()=NAME TO ALL;
GRANT SELECT,UPDATE SALARY ON TABLE EMPLOYEE TO LIUXIN;
GRANT ALTER TABLE ON TABLE EMPLOYEE,DEPARTMENT TO ZHANGXIN;
GRANT ALL PRIVILEGES ON TABLE EMLPOYEE,DEPARTMENT TO ZHOUPING WITH GRANT OPTION;

--4.7.7需要先建立视图
CREATE VIEW DEPARTMENTSALARY AS
SELECT DEPARTMENT.NAME,MAX(SALARY).MIN(SALARY),AVGC(SALARY)
FROM EMPLOYEE,DEPARTMENT
WHERE EMPLOYEE.DEPARTMENT_NUM=DEPARTMENT.DEPARTMENT_NUM
GROUP BY EMPLOYEE.DEPARTMENT_NUM;
GRANT SELECT ON TABIE DEPARTMENTSALARY TO YANGLAN;


--5.6
CREATE TABLE DEPT(
    Deptno NUMBER(2)PRIMARY KEY,
    Deptname VARCHAR(10),
    Manager VARCHAR(10),
    PhoneNumber Char(12)
    );

CREATE TABLE EMP(
    Empno NUMBER(4)PRIMARY KEY,
    Ename VARCHAR(10),
    Age NUMBER(2),
    Job VARCHAR(9),
    Sal NUMBER(7.2),
    Depto NUMBER(2),
        CONSTRAINT CI CHECK(Age<=60),
        CONSTRAINT FK_DEPTNO FOREIGN KEY(Deptno) REFERENCES DEPT(Deptno));